# Generated by Django 4.0.6 on 2023-04-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('IT', 'IT'), ('Non IT', 'Non IT'), ('Mobiles Phones', 'Mobile Phones'), ('Electronics', 'Electronics'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Project Manager', 'Project Manager'), ('Software Developer', 'Software Developer'), ('Team Leader', 'Team Leader'), ('Tester', 'Tester'), ('Digital Marketing', 'Digital Marketer'), ('Content Writer', 'Content Writer'), ('Graphic Designer', 'Graphic Designer'), ('UI/UX Designer', 'UI/UX Designer'), ('HR', 'HR'), ('Accountant', 'Accountant'), ('Sales', 'Sales'), ('Other', 'Other')], max_length=50),
        ),
    ]
